################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,highres,auto,2
# monitor=,preferred,auto,2
xwayland {
  exec-once = echo 'Xft.dpi: 160' | xrdb -merge
  force_zero_scaling = true
}

cursor {
      no_hardware_cursors = true
}
