
# BEGIN_KITTY_THEME
# Everforest Dark Soft
include current-theme.conf
# END_KITTY_THEME

# font
font_size 13
# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# window
hide_window_decorations     titlebar-only
window_padding_width        5
background_opacity          0.95
background_blur             20
remember_window_size        yes

# tab bar
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted

# short key
map f11 toggle_fullscreen
map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i
