#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = fcitx5 &
exec-once = waybar &
exec-once = mako &
# exec-once = udiskie -t &
exec-once = ~/.config/hypr/scripts/random-wallpaper.sh
exec-once = ~/.config/hypr/scripts/udiskie-sound.sh &
# plugins
exec-once = hyprpm reload -n
