###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
#fileManager = dolphin
# $dmenu = rofi -show drun
# $menu = rofi -show run
$dmenu = wofi --show drun
$menu = wofi --show run
