"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
  # Jump
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  # Custom Yank
  { on = [
    "y",
    "y",
  ], run = "yank", desc = "Yank selected files (copy)" },
  { on = [
    "y",
    "x",
  ], run = "yank --cut", desc = "Yank selected files (cut)" },
  { on = [
    "p",
    "p",
  ], run = "paste", desc = "Paste yanked files" },
  { on = [
    "p",
    "P",
  ], run = "paste --force", desc = "Paste yanked files (overwrite)" },
  { on = [
    "p",
    "l",
  ], run = "link", desc = "Symlink the absolute path of yanked files" },
  { on = [
    "p",
    "L",
  ], run = "link --relative", desc = "Symlink the relative path of yanked files" },
  { on = [
    "p",
    "h",
  ], run = "hardlink", desc = "Hardlink yanked files" },

  # Goto
  { on = [
    "g",
    "f",
    'f',
  ], run = "cd ~/dotfiles/", desc = "Go to ~/dotfiles/" },
  { on = [
    "g",
    "f",
    'n',
  ], run = "cd ~/dotfiles/config/nvim/", desc = "Go to the neovim config directory" },
  { on = [
    "g",
    "f",
    'y',
  ], run = "cd ~/dotfiles/config/yazi/", desc = "Go to the yazi config directory" },
  { on = [
    "g",
    "w",
  ], run = "cd ~/workspace", desc = "Go to ~/workspace" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Pictures", desc = "Go to ~/Pictures" },
]
